# Generated by Django 4.2.7 on 2025-11-15 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(help_text='TMDb movie ID')),
                ('title', models.CharField(help_text='Movie title', max_length=255)),
                ('poster_path', models.CharField(blank=True, help_text='Poster image path', max_length=255)),
                ('release_date', models.DateField(blank=True, help_text='Release date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who added to watchlist', on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watchlist',
                'verbose_name_plural': 'Watchlist',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'tmdb_id'], name='users_watch_user_id_1ec6f5_idx'), models.Index(fields=['user', '-created_at'], name='users_watch_user_id_fd79c6_idx')],
                'unique_together': {('user', 'tmdb_id')},
            },
        ),
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(help_text='TMDb movie ID')),
                ('title', models.CharField(help_text='Movie title', max_length=255)),
                ('poster_path', models.CharField(blank=True, help_text='Poster image path', max_length=255)),
                ('release_date', models.DateField(blank=True, help_text='Release date', null=True)),
                ('vote_average', models.FloatField(default=0.0, help_text='Average vote rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who favorited the movie', on_delete=django.db.models.deletion.CASCADE, related_name='favorite_movies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite Movie',
                'verbose_name_plural': 'Favorite Movies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'tmdb_id'], name='users_favor_user_id_ba5841_idx'), models.Index(fields=['user', '-created_at'], name='users_favor_user_id_e7679f_idx')],
                'unique_together': {('user', 'tmdb_id')},
            },
        ),
    ]
