# Generated by Django 4.2.7 on 2025-11-15 12:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(help_text='TMDb genre ID', unique=True)),
                ('name', models.CharField(help_text='Genre name', max_length=100)),
            ],
            options={
                'verbose_name': 'Genre',
                'verbose_name_plural': 'Genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(db_index=True, help_text='TMDb movie ID', unique=True)),
                ('title', models.CharField(help_text='Movie title', max_length=255)),
                ('original_title', models.CharField(blank=True, help_text='Original title', max_length=255)),
                ('overview', models.TextField(blank=True, help_text='Movie overview/description')),
                ('tagline', models.CharField(blank=True, help_text='Movie tagline', max_length=255)),
                ('release_date', models.DateField(blank=True, help_text='Release date', null=True)),
                ('runtime', models.IntegerField(blank=True, help_text='Runtime in minutes', null=True)),
                ('vote_average', models.FloatField(default=0.0, help_text='Average vote rating', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('vote_count', models.IntegerField(default=0, help_text='Number of votes')),
                ('popularity', models.FloatField(default=0.0, help_text='Popularity score')),
                ('poster_path', models.CharField(blank=True, help_text='Poster image path', max_length=255)),
                ('backdrop_path', models.CharField(blank=True, help_text='Backdrop image path', max_length=255)),
                ('original_language', models.CharField(blank=True, help_text='Original language code', max_length=10)),
                ('adult', models.BooleanField(default=False, help_text='Adult content flag')),
                ('video', models.BooleanField(default=False, help_text='Has video flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='movies.genre')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-popularity', '-vote_average'],
                'indexes': [models.Index(fields=['tmdb_id'], name='movies_movi_tmdb_id_0e4cad_idx'), models.Index(fields=['-popularity'], name='movies_movi_popular_3c541f_idx'), models.Index(fields=['-vote_average'], name='movies_movi_vote_av_12ed28_idx'), models.Index(fields=['release_date'], name='movies_movi_release_b7ac7d_idx')],
            },
        ),
    ]
